<?php

namespace App\Observers;

use App\Models\Payment;
use App\Models\User;
use App\Services\WhatsappService;
use Carbon\Carbon;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class PaymentObserver
{
    /**
     * Handle the Payment "created" event.
     */
    public function created(Payment $payment): void
    {
        $whatsappService = new WhatsappService();

        Log::info('A new payment has been created: ' . $payment->id);
        try {
            $whatsappService->sendMessage(
                whatsappNumber($payment->phone),
                "Halo Bapak/Ibu " . $payment->name . ",\n\n" .
                    "Terima kasih telah melakukan pembayaran. Berikut adalah detail pembayarannya:\n\n" .
                    "INVOICE: " . ($payment->paymentInvoice->invoice_number ?? "0000") . "/JRNL/UINSMDD/" . ($payment->paymentInvoice->created_at->format('Y') ?? Carbon::now()->format('Y')) . "\n" .
                    "Jurnal: " . ($payment->paymentInvoice->submission->issue->journal->title ?? '-') . "\n" .
                    "Edisi: " . 'Vol. ' . $payment->paymentInvoice->submission->issue->volume . ' No. ' . $payment->paymentInvoice->submission->issue->number . ' Tahun ' . $payment->paymentInvoice->submission->issue->year . "\n" .
                    "Submission ID: " . ($payment->paymentInvoice->submission->submission_id ?? '-') . "\n\n" .

                    "Telah dibayar oleh: " . "\n" .
                    "Nama: " . $payment->name . "\n" .
                    "Email: " . $payment->email . "\n" .
                    "No. Telepon: " . $payment->phone . "\n" .
                    "Metode Pembayaran: " . $payment->payment_method . "\n" .
                    "No. Rekening: " . $payment->payment_account_number . "\n" .
                    "Atas Nama: " . $payment->payment_account_name . "\n" .
                    "Jumlah: " . $payment->paymentInvoice->payment_amount . "\n" .
                    "Persentase Pembayaran: " . ($payment->paymentInvoice->payment_percent ?? '-') . "%" . "\n\n" .

                    "Pembayaran Anda akan segera kami proses. Terima kasih atas kepercayaan Anda.\n" .
                    "Salam,\n" .
                    "Editorial Rumah Jurnal\n\n" .

                    "_generated by system_" . "\n" .
                    url('/'),
            );


            // $response_wa = Http::post(env('WHATSAPP_API_URL')  . "/send-message", [
            //     'session' => env('WHATSAPP_API_SESSION'),
            //     'to' => whatsappNumber($payment->phone),
            //     'text' => "Halo Bapak/Ibu " . $payment->name . ",\n\n" .
            //         "Terima kasih telah melakukan pembayaran. Berikut adalah detail pembayarannya:\n\n" .
            //         "INVOICE: " . ($payment->paymentInvoice->invoice_number ?? "0000") . "/JRNL/UINSMDD/" . ($payment->paymentInvoice->created_at->format('Y') ?? Carbon::now()->format('Y')) . "\n" .
            //         "Jurnal: " . ($payment->paymentInvoice->submission->issue->journal->title ?? '-') . "\n" .
            //         "Edisi: " . 'Vol. ' . $payment->paymentInvoice->submission->issue->volume . ' No. ' . $payment->paymentInvoice->submission->issue->number . ' Tahun ' . $payment->paymentInvoice->submission->issue->year . "\n" .
            //         "Submission ID: " . ($payment->paymentInvoice->submission->submission_id ?? '-') . "\n\n" .

            //         "Telah dibayar oleh: " . "\n" .
            //         "Nama: " . $payment->name . "\n" .
            //         "Email: " . $payment->email . "\n" .
            //         "No. Telepon: " . $payment->phone . "\n" .
            //         "Metode Pembayaran: " . $payment->payment_method . "\n" .
            //         "No. Rekening: " . $payment->payment_account_number . "\n" .
            //         "Atas Nama: " . $payment->payment_account_name . "\n" .
            //         "Jumlah: " . $payment->paymentInvoice->payment_amount . "\n" .
            //         "Persentase Pembayaran: " . ($payment->paymentInvoice->payment_percent ?? '-') . "%" . "\n\n" .

            //         "Pembayaran Anda akan segera kami proses. Terima kasih atas kepercayaan Anda.\n" .
            //         "Salam,\n" .
            //         "Editorial Rumah Jurnal\n\n" .

            //         "_generated by system_" . "\n" .
            //         url('/'),
            // ]);

            // if ($response_wa->status() != 200) {
            //     Log::error('Failed to send message to ' . $payment->phone . '. Response: ' . $response_wa->body());
            // } else {
            //     Log::info('Message sent to ' . $payment->phone);
            // }
        } catch (\Throwable $th) {
            Log::error('Failed to send payment creation message: ' . $th->getMessage());
        }
        try {
            $user_super_admins = User::role(['super-admin', 'keuangan'])->get();
            $data = [];
            foreach ($user_super_admins as $admin) {
                $whatsappService->sendMessage(
                    env('MAIL_ENVIRONMENT') == 'production' ? whatsappNumber($admin->phone) : whatsappNumber(env('WHATSAPP_ADMIN_NUMBER')),
                    "Halo Bapak/Ibu " . $admin->name . ",\n\n" .
                        "🔔 Ada Pembayaran Masuk dari Rumah Jurnal. " .
                        "Konfirmasi Pembayaran  dari Penulis. Berikut adalah detail pembayarannya:\n\n" .
                        "INVOICE: " . ($payment->paymentInvoice->invoice_number ?? "0000") . "/JRNL/UINSMDD/" . ($payment->paymentInvoice->created_at->format('Y') ?? Carbon::now()->format('Y')) . "\n" .
                        "Jurnal: " . ($payment->paymentInvoice->submission->issue->journal->title ?? '-') . "\n" .
                        "Edisi: " . 'Vol. ' . $payment->paymentInvoice->submission->issue->volume . ' No. ' . $payment->paymentInvoice->submission->issue->number . ' Tahun ' . $payment->paymentInvoice->submission->issue->year . "\n" .
                        "Submission ID: " . ($payment->paymentInvoice->submission->submission_id ?? '-') . "\n\n" .

                        "Telah dibayar oleh: " . "\n" .
                        "Nama: " . $payment->name . "\n" .
                        "Email: " . $payment->email . "\n" .
                        "No. Telepon: " . $payment->phone . "\n" .
                        "Metode Pembayaran: " . $payment->payment_method . "\n" .
                        "No. Rekening: " . $payment->payment_account_number . "\n" .
                        "Atas Nama: " . $payment->payment_account_name . "\n" .
                        "Jumlah: " . $payment->paymentInvoice->payment_amount . "\n" .
                        "Persentase Pembayaran: " . ($payment->paymentInvoice->payment_percent ?? '-') . "%" . "\n" .

                        "Silakan cek sistem untuk memproses pembayaran ini lebih lanjut.\n\n" .

                        "_generated by system_" . "\n" .
                        url('/'),
                );
            }

            if (empty($data)) {
                Log::warning('No super-admin users found to notify about new payment: ' . $payment->id);
                return;
            }
        } catch (\Exception $e) {
            Log::error('Failed to send payment acceptance email: ' . $e->getMessage());
        }
    }

    /**
     * Handle the Payment "updated" event.
     */
    public function updated(Payment $payment): void
    {
        $whatsappService = new WhatsappService();
        if ($payment->payment_status == "accepted") {
            Log::info('Payment has been accepted: ' . $payment->id);

            $doc_path = 'arsip/payment/' . $payment->paymentInvoice->created_at->format('Y') . '/' . $payment->paymentInvoice->invoice_number . '/confirm-payment-' . $payment->paymentInvoice->submission->submission_id . '.pdf';
            try {
                $whatsappService->sendMessage(
                    whatsappNumber($payment->phone),
                    "Halo Bapak/Ibu " . $payment->name . ",\n\n" .
                        "Pembayaran artikel anda telah kami terima dan telah kami konfirmasi. Berikut adalah detail pembayarannya:\n\n" .
                        "INVOICE: " . ($payment->paymentInvoice->invoice_number ?? "0000") . "/JRNL/UINSMDD/" . ($payment->paymentInvoice->created_at->format('Y') ?? Carbon::now()->format('Y')) . "\n" .
                        "Jurnal: " . ($payment->paymentInvoice->submission->issue->journal->title ?? '-') . "\n" .
                        "Edisi: " . 'Vol. ' . $payment->paymentInvoice->submission->issue->volume . ' No. ' . $payment->paymentInvoice->submission->issue->number . ' Tahun ' . $payment->paymentInvoice->submission->issue->year . "\n" .
                        "Submission ID: " . ($payment->paymentInvoice->submission->submission_id ?? '-') . "\n" .
                        "Note: " . ($payment->payment_note ?? '-') . "\n\n" .

                        "Kami juga menyertakan file bukti konfirmasi pembayaran Anda pada pesan ini, jika tidak terkirim anda dapat mengunduhnya melalui tautan berikut:\n" .
                        asset('storage/' . $doc_path) . "\n\n" .

                        "Salam,\n" .
                        "Editorial Rumah Jurnal\n\n" .

                        "_generated by system_" . "\n" .
                        url('/'),
                );

                $whatsappService->sendDocument(
                    whatsappNumber($payment->phone),
                    asset('storage/' . $doc_path),
                    'confirm-payment-' . $payment->paymentInvoice->invoice_number . '.pdf',
                    'application/pdf'
                );

                // Http::post(env('WHATSAPP_API_URL')  . "/send-document", [
                //     'session' => env('WHATSAPP_API_SESSION'),
                //     'to' => whatsappNumber($payment->phone),
                //     'urlDocument' => asset('storage/' . $doc_path),
                //     'filename' => 'confirm-payment-' . $payment->paymentInvoice->invoice_number . '.pdf',
                //     'caption' => "Bukti Konfirmasi Pembayaran Anda\n\n" .
                //         "_generated by System_" . "\n" .
                //         url('/'),
                // ]);
            } catch (\Exception $e) {
                Log::error('Failed to send payment acceptance email: ' . $e->getMessage());
            }

            try {
                $user_super_admins = User::role(['super-admin'])->get();
                $data = [];
                foreach ($user_super_admins as $admin) {

                    $whatsappService->sendMessage(
                        env('MAIL_ENVIRONMENT') == 'production' ? whatsappNumber($admin->phone) : whatsappNumber(env('WHATSAPP_ADMIN_NUMBER')),
                        "Halo Bapak/Ibu " . $admin->name . ",\n\n" .
                            "✅ Pembayaran dari penulis telah disetujui oleh operator keuangan. Berikut adalah detail pembayarannya:\n\n" .
                            "INVOICE: " . ($payment->paymentInvoice->invoice_number ?? "0000") . "/JRNL/UINSMDD/" . ($payment->paymentInvoice->created_at->format('Y') ?? Carbon::now()->format('Y')) . "\n" .
                            "Jurnal: " . ($payment->paymentInvoice->submission->issue->journal->title ?? '-') . "\n" .
                            "Edisi: " . 'Vol. ' . $payment->paymentInvoice->submission->issue->volume . ' No. ' . $payment->paymentInvoice->submission->issue->number . ' Tahun ' . $payment->paymentInvoice->submission->issue->year . "\n" .
                            "Submission ID: " . ($payment->paymentInvoice->submission->submission_id ?? '-') . "\n\n" .
                            "_generated by system_" . "\n" .
                            url('/'),
                    );
                }
                if (empty($data)) {
                    Log::warning('No super-admin users found to notify about payment: ' . $payment->id);
                    return;
                }
            } catch (\Exception $e) {
                Log::error('Failed to send payment acceptance email: ' . $e->getMessage());
            }
        } elseif ($payment->payment_status == "rejected") {
            Log::info('Payment has been rejected: ' . $payment->id);

            try {

                $whatsappService->sendMessage(
                    whatsappNumber($payment->phone),
                    "Halo " . $payment->name . ",\n\n" .
                        "Kami menyesal memberitahukan bahwa pembayaran artikel anda telah ditolak. Berikut adalah detail pembayarannya:\n\n" .
                        "INVOICE: " . ($payment->paymentInvoice->invoice_number ?? "0000") . "/JRNL/UINSMDD/" . ($payment->paymentInvoice->created_at->format('Y') ?? Carbon::now()->format('Y')) . "\n" .
                        "Jurnal: " . ($payment->paymentInvoice->submission->issue->journal->title ?? '-') . "\n" .
                        "Edisi: " . 'Vol. ' . $payment->paymentInvoice->submission->issue->volume . ' No. ' . $payment->paymentInvoice->submission->issue->number . ' Tahun ' . $payment->paymentInvoice->submission->issue->year . "\n" .
                        "Submission ID: " . ($payment->paymentInvoice->submission->submission_id ?? '-') . "\n" .
                        "Alasan penolakan: " . ($payment->payment_note ?? '-') . "\n\n" .
                        "Jika Anda memiliki pertanyaan, silakan hubungi kami.\n\n" .

                        "Salam,\n" .
                        "Editorial Rumah Jurnal\n\n" .

                        "_generated by system_" . "\n" .
                        url('/'),
                );
            } catch (\Exception $e) {
                Log::error('Failed to send payment rejection email: ' . $e->getMessage());
            }
        }
    }

    /**
     * Handle the Payment "deleted" event.
     */
    public function deleted(Payment $payment): void
    {
        //
    }

    /**
     * Handle the Payment "restored" event.
     */
    public function restored(Payment $payment): void
    {
        //
    }

    /**
     * Handle the Payment "force deleted" event.
     */
    public function forceDeleted(Payment $payment): void
    {
        //
    }
}
